apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-app:9090
    isDefault: false
    jsonData:
      timeInterval: "5s"
    editable: true