apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      serviceMap:
        datasourceUid: 'Prometheus'
      tracesToLogs:
        datasourceUid: 'Loki'
        filterByTraceID: true
        filterBySpanID: false