{
 "title": "Go Application Dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"the-app\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"the-app\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"the-app\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"the-app\",handler!=\"none\"} / http_request_duration_seconds_count{job=\"the-app\",handler!=\"none\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Duration [s] - p60",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.6, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Item Operations (per/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation, status) (rate(item_operations_total{job=\"the-app\"}[1m]))",
     "legendFormat": "{{operation}} - {{status}}"
    }
   ]
  },
  {
   "title": "Search Requests (per/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(search_requests_total{job=\"the-app\"}[1m])",
     "legendFormat": "searches"
    }
   ]
  },
  {
   "title": "Search Result Count (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(search_results_count_bucket{job=\"the-app\"}[2m])) by (le))",
     "legendFormat": "p90 results"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"the-app\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"the-app\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Logger Stream",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{job=\"docker-logs\", service_name=\"the-app\"}"
    }
   ]
  }
 ]
}